#!/bin/sh
mvn clean package && docker build -t hiromix222/demo .
docker rm -f demo 2>/dev/null || true && docker run -it --name demo -p 8080:8080 -p 4848:4848 -p 8181:8181 --name demo hiromix222/demo
