#!/bin/sh
#deploy="false"
deploy="true"

image=demo
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t hiromix222/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push hiromix222/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag hiromix222/${image}:1.0-SNAPSHOT hiromix222/${image}:latest
        docker push hiromix222/${image}:latest
    fi
fi